# Dependencies
markdown:            kramdown
highlighter:         rouge

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           /:year/:month/:day/:title/

# Setup
title:               'KKXUE'
name:                'KKXUE Blog'
tagline:             'A blog about Practise in SDN and OpenStack'
description:         'My blog about everything related to SDN, NFV, Virtualization and Cloud'
url:                 http://kkxue.github.io
baseurl:             /
paginate:            5

# About/contact
author:
  name:              KKXUE
  url:               https://kkxue.github.io
  email:             xueguanwen@gmail.com

# Custom vars
version:             1.0.0
